services:
  - type: web
    name: xautomate-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: POST_HEADLESS
        value: "true"
      - key: PUPPETEER_CACHE_DIR
        value: .cache/puppeteer
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: xautomate
      - key: X_USERNAME
        sync: false
      - key: X_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
